### PR TITLE
Make sceptre a dev dependency

### PR DESCRIPTION
**Pull request by zaro0508**
Captain @jfalkenstein says sceptre is a dev dependency so we are going to do as he instructs.

### CODE REVIEW

**Review by jfalkenstein — CHANGES_REQUESTED** [review]
You should make the dev dependencies optional.

**Comment by tarkatronic** [comment]
> You should make the dev dependencies optional.

I'm not sure I understand your intent here. Making these optional isn't really necessary. Dev dependencies only get installed when you run `poetry install` from a full clone of the project. They will never be installed when a user installs the built wheel published to PyPI.

**Comment by jfalkenstein** [comment]
@tarkatronic This is news to me! Thanks for adding that clarification! I've only ever used Poetry for an application and run `poetry install`. I've never used it for built wheels. @zaro0508 apparently I'm full of nonsense, so feel free to ignore my babbling on this point.

**Comment by zaro0508** [comment]
thanks @tarkatronic, we had a [discussion regarding changing sceptre from option to dev dependency in slack](https://og-aws.slack.com/archives/C01JNN8RGBB/p1680533602306499?thread_ts=1680447848.966729&cid=C01JNN8RGBB)

would you guys be able to take another look now?

**Review by tarkatronic — APPROVED** [review]

**Review by jfalkenstein — APPROVED** [review]

**Pull request merged**
